jobs:
  build:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run flake8
          name: Linting
orbs:
  python: circleci/python@1.3.2
version: 2.1
workflows:
  main:
    jobs:
      - build
